export const BOOKS = [
  {
    order: 1,
    slug: 'Genesis',
    korean: '창세기',
    abbreviation: '창',
    chapters: 50,
    testament: 'old',
    aliases: ['창세기', '창', 'genesis', 'gen', 'Genesis'],
  },
  {
    order: 2,
    slug: 'Exodus',
    korean: '출애굽기',
    abbreviation: '출',
    chapters: 40,
    testament: 'old',
    aliases: ['출애굽기', '출', 'exodus', 'exo', 'ex', 'Exodus'],
  },
  {
    order: 3,
    slug: 'Leviticus',
    korean: '레위기',
    abbreviation: '레',
    chapters: 27,
    testament: 'old',
    aliases: ['레위기', '레', 'leviticus', 'lev', 'Leviticus'],
  },
  {
    order: 4,
    slug: 'Numbers',
    korean: '민수기',
    abbreviation: '민',
    chapters: 36,
    testament: 'old',
    aliases: ['민수기', '민', 'numbers', 'num', 'Numbers'],
  },
  {
    order: 5,
    slug: 'Deuteronomy',
    korean: '신명기',
    abbreviation: '신',
    chapters: 34,
    testament: 'old',
    aliases: ['신명기', '신', 'deuteronomy', 'deut', 'dt', 'Deuteronomy'],
  },
  {
    order: 6,
    slug: 'Joshua',
    korean: '여호수아',
    abbreviation: '수',
    chapters: 24,
    testament: 'old',
    aliases: ['여호수아', '수', 'joshua', 'josh', 'Joshua'],
  },
  {
    order: 7,
    slug: 'Judges',
    korean: '사사기',
    abbreviation: '삿',
    chapters: 21,
    testament: 'old',
    aliases: ['사사기', '삿', 'judges', 'judg', 'Judges'],
  },
  {
    order: 8,
    slug: 'Ruth',
    korean: '룻기',
    abbreviation: '룻',
    chapters: 4,
    testament: 'old',
    aliases: ['룻기', '룻', 'ruth', 'ru', 'Ruth'],
  },
  {
    order: 9,
    slug: '1Samuel',
    korean: '사무엘상',
    abbreviation: '삼상',
    chapters: 31,
    testament: 'old',
    aliases: ['사무엘상', '삼상', '1samuel', '1sam', 'firstsamuel', '1Samuel'],
  },
  {
    order: 10,
    slug: '2Samuel',
    korean: '사무엘하',
    abbreviation: '삼하',
    chapters: 24,
    testament: 'old',
    aliases: ['사무엘하', '삼하', '2samuel', '2sam', 'secondsamuel', '2Samuel'],
  },
  {
    order: 11,
    slug: '1Kings',
    korean: '열왕기상',
    abbreviation: '왕상',
    chapters: 22,
    testament: 'old',
    aliases: ['열왕기상', '왕상', '1kings', '1kgs', 'firstkings', '1Kings'],
  },
  {
    order: 12,
    slug: '2Kings',
    korean: '열왕기하',
    abbreviation: '왕하',
    chapters: 25,
    testament: 'old',
    aliases: ['열왕기하', '왕하', '2kings', '2kgs', 'secondkings', '2Kings'],
  },
  {
    order: 13,
    slug: '1Chronicles',
    korean: '역대상',
    abbreviation: '대상',
    chapters: 29,
    testament: 'old',
    aliases: [
      '역대상',
      '대상',
      '1chronicles',
      '1chr',
      'firstchronicles',
      '1Chronicles',
    ],
  },
  {
    order: 14,
    slug: '2Chronicles',
    korean: '역대하',
    abbreviation: '대하',
    chapters: 36,
    testament: 'old',
    aliases: [
      '역대하',
      '대하',
      '2chronicles',
      '2chr',
      'secondchronicles',
      '2Chronicles',
    ],
  },
  {
    order: 15,
    slug: 'Ezra',
    korean: '에스라',
    abbreviation: '스',
    chapters: 10,
    testament: 'old',
    aliases: ['에스라', '스', 'ezra', 'ezr', 'Ezra'],
  },
  {
    order: 16,
    slug: 'Nehemiah',
    korean: '느헤미야',
    abbreviation: '느',
    chapters: 13,
    testament: 'old',
    aliases: ['느헤미야', '느', 'nehemiah', 'neh', 'Nehemiah'],
  },
  {
    order: 17,
    slug: 'Esther',
    korean: '에스더',
    abbreviation: '에',
    chapters: 10,
    testament: 'old',
    aliases: ['에스더', '에', 'esther', 'est', 'Esther'],
  },
  {
    order: 18,
    slug: 'Job',
    korean: '욥기',
    abbreviation: '욥',
    chapters: 42,
    testament: 'old',
    aliases: ['욥기', '욥', 'job', 'Job'],
  },
  {
    order: 19,
    slug: 'Psalms',
    korean: '시편',
    abbreviation: '시',
    chapters: 150,
    testament: 'old',
    aliases: ['시편', '시', 'psalms', 'psalm', 'ps', 'Psalms'],
  },
  {
    order: 20,
    slug: 'Proverbs',
    korean: '잠언',
    abbreviation: '잠',
    chapters: 31,
    testament: 'old',
    aliases: ['잠언', '잠', 'proverbs', 'prov', 'pr', 'Proverbs'],
  },
  {
    order: 21,
    slug: 'Ecclesiastes',
    korean: '전도서',
    abbreviation: '전',
    chapters: 12,
    testament: 'old',
    aliases: ['전도서', '전', 'ecclesiastes', 'eccl', 'ecc', 'Ecclesiastes'],
  },
  {
    order: 22,
    slug: 'SongofSolomon',
    korean: '아가',
    abbreviation: '아',
    chapters: 8,
    testament: 'old',
    aliases: [
      '아가',
      '아',
      'songofsolomon',
      'song',
      'songs',
      'sos',
      'SongofSolomon',
    ],
  },
  {
    order: 23,
    slug: 'Isaiah',
    korean: '이사야',
    abbreviation: '사',
    chapters: 66,
    testament: 'old',
    aliases: ['이사야', '사', 'isaiah', 'isa', 'Isaiah'],
  },
  {
    order: 24,
    slug: 'Jeremiah',
    korean: '예레미야',
    abbreviation: '렘',
    chapters: 52,
    testament: 'old',
    aliases: ['예레미야', '렘', 'jeremiah', 'jer', 'Jeremiah'],
  },
  {
    order: 25,
    slug: 'Lamentations',
    korean: '예레미야애가',
    abbreviation: '애',
    chapters: 5,
    testament: 'old',
    aliases: ['예레미야애가', '애', 'lamentations', 'lam', 'Lamentations'],
  },
  {
    order: 26,
    slug: 'Ezekiel',
    korean: '에스겔',
    abbreviation: '겔',
    chapters: 48,
    testament: 'old',
    aliases: ['에스겔', '겔', 'ezekiel', 'ezek', 'Ezekiel'],
  },
  {
    order: 27,
    slug: 'Daniel',
    korean: '다니엘',
    abbreviation: '단',
    chapters: 12,
    testament: 'old',
    aliases: ['다니엘', '단', 'daniel', 'dan', 'Daniel'],
  },
  {
    order: 28,
    slug: 'Hosea',
    korean: '호세아',
    abbreviation: '호',
    chapters: 14,
    testament: 'old',
    aliases: ['호세아', '호', 'hosea', 'hos', 'Hosea'],
  },
  {
    order: 29,
    slug: 'Joel',
    korean: '요엘',
    abbreviation: '욜',
    chapters: 3,
    testament: 'old',
    aliases: ['요엘', '욜', 'joel', 'Joel'],
  },
  {
    order: 30,
    slug: 'Amos',
    korean: '아모스',
    abbreviation: '암',
    chapters: 9,
    testament: 'old',
    aliases: ['아모스', '암', 'amos', 'am', 'Amos'],
  },
  {
    order: 31,
    slug: 'Obadiah',
    korean: '오바댜',
    abbreviation: '옵',
    chapters: 1,
    testament: 'old',
    aliases: ['오바댜', '옵', 'obadiah', 'obad', 'Obadiah'],
  },
  {
    order: 32,
    slug: 'Jonah',
    korean: '요나',
    abbreviation: '욘',
    chapters: 4,
    testament: 'old',
    aliases: ['요나', '욘', 'jonah', 'jon', 'Jonah'],
  },
  {
    order: 33,
    slug: 'Micah',
    korean: '미가',
    abbreviation: '미',
    chapters: 7,
    testament: 'old',
    aliases: ['미가', '미', 'micah', 'mic', 'Micah'],
  },
  {
    order: 34,
    slug: 'Nahum',
    korean: '나훔',
    abbreviation: '나',
    chapters: 3,
    testament: 'old',
    aliases: ['나훔', '나', 'nahum', 'nah', 'Nahum'],
  },
  {
    order: 35,
    slug: 'Habakkuk',
    korean: '하박국',
    abbreviation: '합',
    chapters: 3,
    testament: 'old',
    aliases: ['하박국', '합', 'habakkuk', 'hab', 'Habakkuk'],
  },
  {
    order: 36,
    slug: 'Zephaniah',
    korean: '스바냐',
    abbreviation: '습',
    chapters: 3,
    testament: 'old',
    aliases: ['스바냐', '습', 'zephaniah', 'zeph', 'Zephaniah'],
  },
  {
    order: 37,
    slug: 'Haggai',
    korean: '학개',
    abbreviation: '학',
    chapters: 2,
    testament: 'old',
    aliases: ['학개', '학', 'haggai', 'hag', 'Haggai'],
  },
  {
    order: 38,
    slug: 'Zechariah',
    korean: '스가랴',
    abbreviation: '슥',
    chapters: 14,
    testament: 'old',
    aliases: ['스가랴', '슥', 'zechariah', 'zech', 'Zechariah'],
  },
  {
    order: 39,
    slug: 'Malachi',
    korean: '말라기',
    abbreviation: '말',
    chapters: 4,
    testament: 'old',
    aliases: ['말라기', '말', 'malachi', 'mal', 'Malachi'],
  },
  {
    order: 40,
    slug: 'Matthew',
    korean: '마태복음',
    abbreviation: '마',
    chapters: 28,
    testament: 'new',
    aliases: ['마태복음', '마태', '마', 'matthew', 'matt', 'mt', 'Matthew'],
  },
  {
    order: 41,
    slug: 'Mark',
    korean: '마가복음',
    abbreviation: '막',
    chapters: 16,
    testament: 'new',
    aliases: ['마가복음', '마가', '막', 'mark', 'mk', 'Mark'],
  },
  {
    order: 42,
    slug: 'Luke',
    korean: '누가복음',
    abbreviation: '눅',
    chapters: 24,
    testament: 'new',
    aliases: ['누가복음', '누가', '눅', 'luke', 'lk', 'Luke'],
  },
  {
    order: 43,
    slug: 'John',
    korean: '요한복음',
    abbreviation: '요',
    chapters: 21,
    testament: 'new',
    aliases: ['요한복음', '요한', '요', 'john', 'jn', 'John'],
  },
  {
    order: 44,
    slug: 'Acts',
    korean: '사도행전',
    abbreviation: '행',
    chapters: 28,
    testament: 'new',
    aliases: ['사도행전', '행', 'acts', 'act', 'Acts'],
  },
  {
    order: 45,
    slug: 'Romans',
    korean: '로마서',
    abbreviation: '롬',
    chapters: 16,
    testament: 'new',
    aliases: ['로마서', '롬', 'romans', 'rom', 'Romans'],
  },
  {
    order: 46,
    slug: '1Corinthians',
    korean: '고린도전서',
    abbreviation: '고전',
    chapters: 16,
    testament: 'new',
    aliases: [
      '고린도전서',
      '고전',
      '1corinthians',
      '1cor',
      'firstcorinthians',
      '1Corinthians',
    ],
  },
  {
    order: 47,
    slug: '2Corinthians',
    korean: '고린도후서',
    abbreviation: '고후',
    chapters: 13,
    testament: 'new',
    aliases: [
      '고린도후서',
      '고후',
      '2corinthians',
      '2cor',
      'secondcorinthians',
      '2Corinthians',
    ],
  },
  {
    order: 48,
    slug: 'Galatians',
    korean: '갈라디아서',
    abbreviation: '갈',
    chapters: 6,
    testament: 'new',
    aliases: ['갈라디아서', '갈', 'galatians', 'gal', 'Galatians'],
  },
  {
    order: 49,
    slug: 'Ephesians',
    korean: '에베소서',
    abbreviation: '엡',
    chapters: 6,
    testament: 'new',
    aliases: ['에베소서', '엡', 'ephesians', 'eph', 'Ephesians'],
  },
  {
    order: 50,
    slug: 'Philippians',
    korean: '빌립보서',
    abbreviation: '빌',
    chapters: 4,
    testament: 'new',
    aliases: ['빌립보서', '빌', 'philippians', 'phil', 'php', 'Philippians'],
  },
  {
    order: 51,
    slug: 'Colossians',
    korean: '골로새서',
    abbreviation: '골',
    chapters: 4,
    testament: 'new',
    aliases: ['골로새서', '골', 'colossians', 'col', 'Colossians'],
  },
  {
    order: 52,
    slug: '1Thessalonians',
    korean: '데살로니가전서',
    abbreviation: '살전',
    chapters: 5,
    testament: 'new',
    aliases: [
      '데살로니가전서',
      '살전',
      '1thessalonians',
      '1thess',
      '1th',
      '1Thessalonians',
    ],
  },
  {
    order: 53,
    slug: '2Thessalonians',
    korean: '데살로니가후서',
    abbreviation: '살후',
    chapters: 3,
    testament: 'new',
    aliases: [
      '데살로니가후서',
      '살후',
      '2thessalonians',
      '2thess',
      '2th',
      '2Thessalonians',
    ],
  },
  {
    order: 54,
    slug: '1Timothy',
    korean: '디모데전서',
    abbreviation: '딤전',
    chapters: 6,
    testament: 'new',
    aliases: ['디모데전서', '딤전', '1timothy', '1tim', '1Timothy'],
  },
  {
    order: 55,
    slug: '2Timothy',
    korean: '디모데후서',
    abbreviation: '딤후',
    chapters: 4,
    testament: 'new',
    aliases: ['디모데후서', '딤후', '2timothy', '2tim', '2Timothy'],
  },
  {
    order: 56,
    slug: 'Titus',
    korean: '디도서',
    abbreviation: '딛',
    chapters: 3,
    testament: 'new',
    aliases: ['디도서', '딛', 'titus', 'tit', 'Titus'],
  },
  {
    order: 57,
    slug: 'Philemon',
    korean: '빌레몬서',
    abbreviation: '몬',
    chapters: 1,
    testament: 'new',
    aliases: ['빌레몬서', '몬', 'philemon', 'phlm', 'Philemon'],
  },
  {
    order: 58,
    slug: 'Hebrews',
    korean: '히브리서',
    abbreviation: '히',
    chapters: 13,
    testament: 'new',
    aliases: ['히브리서', '히', 'hebrews', 'heb', 'Hebrews'],
  },
  {
    order: 59,
    slug: 'James',
    korean: '야고보서',
    abbreviation: '약',
    chapters: 5,
    testament: 'new',
    aliases: ['야고보서', '약', 'james', 'jas', 'James'],
  },
  {
    order: 60,
    slug: '1Peter',
    korean: '베드로전서',
    abbreviation: '벧전',
    chapters: 5,
    testament: 'new',
    aliases: ['베드로전서', '벧전', '1peter', '1pet', '1pe', '1Peter'],
  },
  {
    order: 61,
    slug: '2Peter',
    korean: '베드로후서',
    abbreviation: '벧후',
    chapters: 3,
    testament: 'new',
    aliases: ['베드로후서', '벧후', '2peter', '2pet', '2pe', '2Peter'],
  },
  {
    order: 62,
    slug: '1John',
    korean: '요한1서',
    abbreviation: '요일',
    chapters: 5,
    testament: 'new',
    aliases: ['요한1서', '요일', '1john', '1jn', '1j', '1John'],
  },
  {
    order: 63,
    slug: '2John',
    korean: '요한2서',
    abbreviation: '요이',
    chapters: 1,
    testament: 'new',
    aliases: ['요한2서', '요이', '2john', '2jn', '2j', '2John'],
  },
  {
    order: 64,
    slug: '3John',
    korean: '요한3서',
    abbreviation: '요삼',
    chapters: 1,
    testament: 'new',
    aliases: ['요한3서', '요삼', '3john', '3jn', '3j', '3John'],
  },
  {
    order: 65,
    slug: 'Jude',
    korean: '유다서',
    abbreviation: '유',
    chapters: 1,
    testament: 'new',
    aliases: ['유다서', '유', 'jude', 'jud', 'Jude'],
  },
  {
    order: 66,
    slug: 'Revelation',
    korean: '요한계시록',
    abbreviation: '계',
    chapters: 22,
    testament: 'new',
    aliases: ['요한계시록', '계', 'revelation', 'rev', 'Revelation'],
  },
] as const

export type Book = (typeof BOOKS)[number]
export type BookSlug = Book['slug']
export type Testament = Book['testament']

export const TOTAL_BOOKS = BOOKS.length
export const TOTAL_CHAPTERS = BOOKS.reduce(
  (sum, book) => sum + book.chapters,
  0,
)

export function isBookSlug(value: string): value is BookSlug {
  return BOOKS.some((book) => book.slug === value)
}

export function getBookBySlug(slug: string): Book | undefined {
  return BOOKS.find((book) => book.slug === slug)
}

export function getBookByAlias(input: string): Book | undefined {
  const normalized = normalizeAlias(input)
  return BOOKS.find((book) =>
    book.aliases.some((alias) => normalizeAlias(alias) === normalized),
  )
}

export function normalizeAlias(input: string): string {
  return input.normalize('NFC').replace(/\s+/g, '').toLowerCase()
}

export const BOOK_ALIASES = BOOKS.flatMap((book) =>
  book.aliases.map((alias) => ({
    alias,
    normalized: normalizeAlias(alias),
    book,
  })),
).sort((a, b) => b.normalized.length - a.normalized.length)
