export type RuntimeSmokeTarget = {
  label: string
  method: 'GET'
  path: string
  url: string
  kind: 'page' | 'api'
}

export type ApiSmokeValidation = { ok: true } | { ok: false; reason: string }

const PAGE_PATHS = [
  '/',
  '/Psalms/23',
  '/Psalms/23/5',
  '/Psalms/23/5/live',
  '/read/Psalms/23',
  '/service/today',
] as const

const API_PATHS = [
  '/api/service-plans/migration-smoke',
  '/api/live-sessions/migration-smoke',
] as const

export function normalizeBaseUrl(baseUrl: string): string {
  const trimmed = baseUrl.trim().replace(/\/+$/, '')
  if (!trimmed) throw new Error('Missing --base-url')
  const parsed = new URL(trimmed)
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('Smoke base URL must be http or https')
  }
  return parsed.toString().replace(/\/$/, '')
}

export function buildRuntimeSmokeTargets(
  baseUrl: string,
): RuntimeSmokeTarget[] {
  const normalized = normalizeBaseUrl(baseUrl)
  return [
    ...PAGE_PATHS.map((path) => ({
      label: `GET ${path}`,
      method: 'GET' as const,
      path,
      url: `${normalized}${path === '/' ? '/' : path}`,
      kind: 'page' as const,
    })),
    ...API_PATHS.map((path) => ({
      label: `GET ${path}`,
      method: 'GET' as const,
      path,
      url: `${normalized}${path}`,
      kind: 'api' as const,
    })),
  ]
}

export function isSafeSmokeSlug(slug: string): boolean {
  return /^migration-smoke[a-zA-Z0-9_-]*$/.test(slug)
}

export function validateApiSmokeResponse(body: unknown): ApiSmokeValidation {
  if (!body || typeof body !== 'object') {
    return { ok: false, reason: 'API response is not an object' }
  }
  const record = body as Record<string, unknown>
  if (record['ok'] !== true) {
    return record['ok'] === false
      ? { ok: false, reason: 'API returned ok=false' }
      : { ok: false, reason: 'API response missing ok=true' }
  }
  if (typeof record['configured'] !== 'boolean') {
    return { ok: false, reason: 'API response missing configured boolean' }
  }
  return { ok: true }
}

export function servicePlanSmokePayload(): {
  rawInput: string
  title: string
  notes: string
} {
  return {
    rawInput: '시 23:1-6, 요 14:1-3',
    title: 'Migration smoke service',
    notes: 'Generated by bible1 migration smoke. Safe to delete.',
  }
}

export function liveSessionSmokePayload(): {
  href: string
  reference: string
  ordinal: number
  number: number
  text: string
  blackout: boolean
} {
  return {
    href: '/Psalms/23/5',
    reference: '시편 23:5',
    ordinal: 5,
    number: 5,
    text: '공개 저장소용 예시 송출 문장입니다. 실제 성경 본문은 포함되지 않습니다.',
    blackout: false,
  }
}
